name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - .gitignore
      - .github/**
      - LICENSE

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Login to Registry
      uses: docker/login-action@v3
      with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
    
    - name: Build the Docker image
      run: docker buildx build . --platform linux/amd64 --file Dockerfile --tag registry.cloud.cbh.kth.se/waitapp/cicd:latest --push
